
project_id = "zdeivfgqmanwrxrksbld"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://zdeivfgqmanwrxrksbld.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.ai-chat]
verify_jwt = true
