// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdeivfgqmanwrxrksbld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZWl2ZmdxbWFud3J4cmtzYmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzA5NjUsImV4cCI6MjA2MDIwNjk2NX0.1Jnyf6t9yQTeqSkLf4hjl0twAtLSbjhF6MZHlVPw1HI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);